int_1= input("Enter an integer: ")
int_2=input("Enter another integer: ")
int_3= input("Enter a third integer: ")
sum= int(int_1)+int(int_2)+int(int_3)
output= int(int_1) - int(int_2)
output2= int(int_3) * int(int_1)
output3=sum/int(int_3)
print(sum)
print(output)
print(output2)
print(output3)